//! macOS menu-bar item: Open config, Quit.
//!
//! AppKit REQUIRES `NSApplication` on the process main thread, and its run loop never
//! returns. That is why `main()` inverts on this platform: the tokio runtime moves to a
//! spawned thread and the main thread becomes the menu pump. The runtime thread keeps the
//! audio-adjacent priority — `set_qos_user_initiated()` raises whichever thread calls it,
//! and it is called from inside `async_main` — so nothing about scheduling changes. The
//! main thread is now a menu pump at default priority, which is what it should be.
//!
//! Shutting down does not need the two run loops to negotiate. The runtime thread calls
//! `std::process::exit` once `async_main` has returned and the clean shutdown has already
//! run, which ends the AppKit loop with it.
//!
//! The one shutdown AppKit starts itself is a log out, restart or power off: the system asks
//! every running app to quit, and without a delegate NSApplication would end the process on
//! the spot — no config flush, no exclusive-device release. The delegate below turns that
//! request into the same clean shutdown every other path takes.
//!
//! `LSUIElement` in the bundle's Info.plist already makes this an agent app — no Dock icon,
//! no application menu — and `Accessory` below is the equivalent for a run from a terminal,
//! where there is no Info.plist to read.

use std::ffi::c_void;
use std::sync::atomic::{AtomicU16, Ordering};

use objc2::rc::Retained;
use objc2::runtime::{AnyObject, ProtocolObject};
use objc2::{define_class, msg_send, sel, AnyThread, MainThreadOnly};
use objc2_app_kit::{
    NSAlert, NSAlertStyle, NSApplication, NSApplicationActivationPolicy,
    NSApplicationDelegate, NSApplicationTerminateReply, NSImage, NSMenu, NSMenuItem,
    NSStatusBar, NSVariableStatusItemLength, NSWorkspace,
};
use objc2_foundation::{
    ns_string, MainThreadMarker, NSData, NSObject, NSObjectProtocol, NSSize, NSString, NSURL,
};

/// How long a system-requested quit waits for the clean shutdown before ending the process
/// anyway. The shutdown normally finishes well inside a second; this only bounds a hang, and
/// stays short of the point where the system gives up on the app and cancels the log out.
const TERMINATE_WAIT: std::time::Duration = std::time::Duration::from_secs(4);

/// The web UI's port, published by the daemon once config is loaded. 0 means "not up yet".
static API_PORT: AtomicU16 = AtomicU16::new(0);

/// The menu-bar image. Generated by `cross/make-icons.py` from the same hexagon the web UI
/// draws, and used as a TEMPLATE: AppKit reads only its alpha and paints it in the system
/// colour, so it follows light and dark menu bars and highlights correctly.
const MENUBAR_PNG: &[u8] = include_bytes!("../../../assets/menubar.png");

/// Tell the menu which port to open. Called once the API is listening.
pub fn set_api_port(port: u16) {
    API_PORT.store(port, Ordering::Relaxed);
}

define_class!(
    #[unsafe(super(NSObject))]
    #[thread_kind = MainThreadOnly]
    #[name = "CascadeMenuTarget"]
    struct MenuTarget;

    unsafe impl NSObjectProtocol for MenuTarget {}

    // Also the application delegate, for the one quit AppKit starts on its own.
    unsafe impl NSApplicationDelegate for MenuTarget {
        /// The system is logging out, restarting or powering off, and has asked this app to
        /// quit. Start the clean shutdown and answer "later": the runtime thread ends the
        /// process once the config is flushed and the device released, which is the answer.
        /// If that has not happened within TERMINATE_WAIT, end it anyway.
        #[unsafe(method(applicationShouldTerminate:))]
        fn application_should_terminate(&self, _sender: &NSApplication)
            -> NSApplicationTerminateReply
        {
            crate::lifecycle::request(crate::lifecycle::Exit::Quit);
            let _ = std::thread::Builder::new()
                .name("cascade-quit-backstop".into())
                .spawn(|| {
                    std::thread::sleep(TERMINATE_WAIT);
                    std::process::exit(0);
                });
            NSApplicationTerminateReply::TerminateLater
        }
    }

    impl MenuTarget {
        #[unsafe(method(openConfig:))]
        fn open_config(&self, _sender: Option<&AnyObject>) {
            let port = API_PORT.load(Ordering::Relaxed);
            if port == 0 {
                return; // still starting; nothing to open yet
            }
            // Loopback explicitly. `bind` may be 0.0.0.0, which is not an address to browse
            // to, and the port comes from config rather than being assumed.
            let url = NSString::from_str(&format!("http://127.0.0.1:{port}/"));
            if let Some(u) = NSURL::URLWithString(&url) {
                NSWorkspace::sharedWorkspace().openURL(&u);
            }
        }

        #[unsafe(method(quit:))]
        fn quit(&self, _sender: Option<&AnyObject>) {
            let mtm = MainThreadMarker::from(self);
            if confirm_quit(mtm) {
                // Requests the same shutdown every other path uses: the device claim is
                // released and the config flushed before the process goes.
                crate::lifecycle::request(crate::lifecycle::Exit::Quit);
            }
        }
    }
);

/// One confirmation, defaulting to Cancel, saying what is actually lost. A menu-bar Quit is
/// a single click away from a live broadcast.
fn confirm_quit(mtm: MainThreadMarker) -> bool {
    {
        let app = NSApplication::sharedApplication(mtm);
        // An accessory app is not frontmost, so without this the alert can open behind
        // whatever the user is looking at.
        //
        // activateIgnoringOtherApps: DELIBERATELY, not the newer `activate`. `-[NSApplication
        // activate]` was added in macOS 14, objc2 exposes it with no availability gate, and
        // the bundle's LSMinimumSystemVersion is 11.0 — so on an older system the selector
        // does not exist, the message send raises, and the menu item silently does nothing.
        // This one has existed since 10.0 and still works on current macOS; the deprecation
        // notice says "will be deprecated in a future release", not that it is gone.
        #[allow(deprecated)]
        app.activateIgnoringOtherApps(true);

        let alert = NSAlert::new(mtm);
        alert.setAlertStyle(NSAlertStyle::Warning);
        alert.setMessageText(ns_string!("Quit Cascade?"));
        alert.setInformativeText(ns_string!(
            "All audio being sent to and received from your remotes will stop."
        ));
        // NSAlert gives the FIRST button added the Return key, and any button titled "Cancel"
        // the Escape key. So Cancel goes first: an accidental Return must not end a live
        // broadcast. Quit is the second button, and Escape still cancels.
        alert.addButtonWithTitle(ns_string!("Cancel"));
        alert.addButtonWithTitle(ns_string!("Quit"));
        // NSAlertSecondButtonReturn — Quit.
        alert.runModal() == 1001
    }
}

fn menubar_image() -> Option<Retained<NSImage>> {
    {
        let data = NSData::with_bytes(MENUBAR_PNG);
        let image = NSImage::initWithData(NSImage::alloc(), &data)?;
        // Menu-bar items are sized in points; 18 is the conventional height for a 22pt bar.
        image.setSize(NSSize::new(18.0, 18.0));
        // Template: AppKit uses the alpha only and paints it in the system colour.
        image.setTemplate(true);
        Some(image)
    }
}

/// Install the menu-bar item and run the AppKit event loop. NEVER RETURNS — the process
/// exits from the runtime thread once the daemon has shut down cleanly.
pub fn run_menu_bar() -> ! {
    let mtm = MainThreadMarker::new()
        .expect("run_menu_bar must be called on the process main thread");

    let app = NSApplication::sharedApplication(mtm);
    // Accessory, not Regular: no Dock icon and no application menu, which is what an agent
    // with a menu-bar item should be. Matches LSUIElement in the bundle's Info.plist and
    // supplies the same behaviour when run from a terminal, where there is no plist.
    app.setActivationPolicy(NSApplicationActivationPolicy::Accessory);

    let target = MenuTarget::alloc(mtm);
    let target: Retained<MenuTarget> = unsafe { msg_send![target, init] };

    unsafe {
        let status_item = NSStatusBar::systemStatusBar()
            .statusItemWithLength(NSVariableStatusItemLength);

        if let Some(button) = status_item.button(mtm) {
            match menubar_image() {
                Some(img) => button.setImage(Some(&img)),
                // Falling back to text keeps the item findable rather than invisible.
                None => button.setTitle(ns_string!("Cascade")),
            }
        }

        let menu = NSMenu::new(mtm);

        let open = NSMenuItem::new(mtm);
        open.setTitle(ns_string!("Open config"));
        open.setAction(Some(sel!(openConfig:)));
        open.setTarget(Some(&target));
        menu.addItem(&open);

        menu.addItem(&NSMenuItem::separatorItem(mtm));

        let quit = NSMenuItem::new(mtm);
        quit.setTitle(ns_string!("Quit Cascade"));
        quit.setAction(Some(sel!(quit:)));
        quit.setTarget(Some(&target));
        menu.addItem(&quit);

        status_item.setMenu(Some(&menu));

        // The application holds its delegate weakly; `target` is kept alive below.
        app.setDelegate(Some(ProtocolObject::from_ref(&*target)));

        // Leaked deliberately: both must outlive this call, and this call outlives the
        // process. Dropping them would remove the item from the menu bar.
        std::mem::forget(status_item);
        std::mem::forget(target);

        app.run();
    }

    // NSApplication::run does not return in normal operation; the process exits from the
    // runtime thread. If it ever does return, treat it as a request to stop.
    crate::lifecycle::request(crate::lifecycle::Exit::Quit);
    std::process::exit(0);
}

/// Show a fatal error in a dialog, and return once it has been dismissed.
///
/// A bundled daemon has no console, so without this a startup failure leaves the app simply
/// not running with nothing on screen. Called from the runtime thread: AppKit needs the main
/// thread, so the alert is run there, synchronously, so the process does not exit under it.
pub fn show_report(title: &str, body: &str) {
    struct Report { title: String, body: String }

    extern "C" fn show(ctx: *mut c_void) {
        // Called from C (the dispatch queue): a panic must not unwind out of it.
        let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            // SAFETY: `ctx` is the `Report` below, alive until dispatch_sync_f returns.
            let report = unsafe { &*(ctx as *const Report) };
            let Some(mtm) = MainThreadMarker::new() else { return };
            // Not frontmost as an accessory app — see confirm_quit.
            #[allow(deprecated)]
            NSApplication::sharedApplication(mtm).activateIgnoringOtherApps(true);
            let alert = NSAlert::new(mtm);
            alert.setAlertStyle(NSAlertStyle::Critical);
            alert.setMessageText(&NSString::from_str(&report.title));
            alert.setInformativeText(&NSString::from_str(&report.body));
            alert.runModal();
        }));
    }

    let report = Report { title: title.to_string(), body: body.to_string() };
    let ctx = &report as *const Report as *mut c_void;
    if MainThreadMarker::new().is_some() {
        show(ctx);   // already on the main thread: dispatching to it would deadlock
        return;
    }
    // SAFETY: the main queue is always valid, and dispatch_sync_f blocks until `show` has
    // run, so `report` outlives every use of `ctx`.
    unsafe { dispatch_sync_f(std::ptr::addr_of!(_dispatch_main_q).cast(), ctx, show) };
}

extern "C" {
    /// The main dispatch queue — `dispatch_get_main_queue()` is a macro for its address.
    static _dispatch_main_q: u8;
    fn dispatch_sync_f(queue: *const c_void, context: *mut c_void,
                       work: extern "C" fn(*mut c_void));
}
